### ISSUE TITLE
Create empty views for each method created in a new controller

### ISSUE THREAD

**Issue by andrewryno** [RobertAudi/fire#2]
This might just be me, but it would be nice if views were created whenever a controller is generated. So if I run "rails generate users index show edit delete", then it would create empty views like:
- application
  - controllers
    - users.php
  - views
    - users
      - index.php
      - show.php
      - edit.php
      - delete.php

It somewhat makes developers conform to this naming structure, but I feel like it's standard enough that this would make it easier to work with views rather than having to make them separately and manually.

Thoughts?

**Comment by RobertAudi** [comment]
Right now, when you create a controller with `fire g controller users index show edit delete` it creates the users controller and the views in the correct folder (`views/users/`). What you are asking, if I understand well, is to have a views generator that would be called like this:

```
% fire g views users
```

This command will parse the users controller and create views for each controller action if the view doesn't already exist.

Did I understand correctly?

If thats the case then I think it's a great idea and I will implement it as soon as I have a free minute ;)

**Comment by andrewryno** [comment]
Actually I was asking the first one. I haven't had a chance to try it out so I must have missed that while looking through the source. My bad. :) Hopefully going to be using it on my next project. Doing migrations manually sucks.

**Comment by RobertAudi** [comment]
OK. By the way, Fire lets you run migrations from the command line :)

I will keep this issue open until I implement the second feature (the views generator) because it's a great idea.

**Comment by andrewryno** [comment]
Yeah the migrations is the main feature that drew me to this. :)

Second feature would definitely be cool, too. Thanks!

**Comment by RobertAudi** [comment]
I implemented the second feature. Closing this issue.
